config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  devise_for :users 
  resources :messages, only: [:index, :new, :create]

  get 'static_pages/about'
  resources :dashboard

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments do
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  validates :user, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :category
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :likes, dependent: :destroy 
  has_many :liked_posts, through: :likes, source: :likeable, source_type: 'Post'
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'receiver_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper :all
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :admin])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
  
    if @comment.save
      redirect_to @post
      flash[:notice] = "Comment created successfully"
    else
      @comments = @post.comments
      render 'posts/show'
      flash.now[:alert] = "Cannot create comment"
    end
  end
    
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.post, notice: 'Comment was successfully deleted.'
  end

  private
   
  def comment_params
    params.require(:comment).permit( :body, :parent_id)
  end
end

app/controllers/dashboard_controller.rb
  class DashboardController  < ApplicationController
  before_action :check_if_admin
   
  def index
    @user = User.all
  end

  private

  def check_if_admin
   unless current_user.admin?
     redirect_to root_path 
     flash[:alert] = "Unauthorized access! You need to be an admin to access the dashboard."
   end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_likeable

  def create
    @like = @likeable.likes.build(user: current_user)
    if @like.save
      flash[:success] = "Liked successfully"
    else
      flash[:error] = "Unable to like"
    end
    redirect_back fallback_location: root_path
  end

  def destroy
    @like = @likeable.likes.find(params[:id])
    if @like.destroy
      flash[:success] = "Unliked successfully"
    else
      flash[:error] = "Unable to unlike"
    end
    redirect_back fallback_location: root_path
  end

  private

  def find_likeable
    if params[:comment_id]
      @likeable = Comment.find_by(id: params[:comment_id])
    elsif params[:post_id]
      @likeable = Post.find_by(id: params[:post_id])
    end

    
    unless @likeable
      flash[:error] = "Likeable object not found"
      redirect_back fallback_location: root_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @received_messages = current_user.received_messages
    @sent_messages = current_user.sent_messages
  end

  def new
    @message = Message.new
  end

  def create
    @message = current_user.sent_messages.build(message_params)
    if @message.save
      redirect_to messages_path, notice: 'Message sent successfully.'
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:sender_id, :receiver_id, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_categories

  def index
    @posts = Post.all.order(:created_at)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = @post.comments.new(parent_id: params[:parent_id])
    @comments = @post.comments.order(id: :desc)
    liking_users = @post.liking_users
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    
      if @post.save
        redirect_to @post
        flash[:notice] = "Post created successfully!"
      else
        render 'new', status: :unprocessable_entity
        flash[:alert] = "Post could not be created!"
      end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to @post
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
    flash[:notice] = "Post deleted successfully!"
 
  end

  private
  
    def post_params
      params.require(:post).permit(:title, :description, :category_id, :user_id)
    end

    def set_categories
      @categories = Category.all.order(:name)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def already_liked?(likeable)
    likeable.likes.where(user_id: current_user.id).exists?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def already_liked?(comment)
    return false unless current_user
    comment.likes.where(user_id: current_user.id).exists?
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/dashboard/index.html.erb
<%= render 'shared/navbar' %>
<div class="container">
<h1 class= "fw-bold">Hello, welcome to admin dashboard</h1>
<h4 class="fw-bold">List of users</h2>
<div class="container">
<% @user.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</div>
</div>

app/views/comments/_comment.html.erb
<% unless comment.parent_id || !comment.persisted? %>
  <div class="p-2">
    <div class="my-2 p-3 bg-light">
      <strong><%= comment.user.name %></strong> : <%= comment.body %>
      <div class="mb-3">
        <% if current_user %>
          <div class="d-flex flex-row">
            <% if current_user.admin? %>
              <%= button_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link p-0' %> |
            <% end %>
            <% unless already_liked?(comment) %>
              <%= button_to 'Like', post_comment_likes_path(comment.post, comment, likeable_type: 'Comment', likeable_id: comment.id), method: :post, class: 'btn btn-link p-0' %>
            <% else %>
              <% like = comment.likes.find_by(user_id: current_user.id) %>
              <%= button_to 'Unlike', post_comment_like_path(comment.post, comment, id: like.id, likeable_type: 'Comment', likeable_id: comment.id), method: :delete, class: 'btn btn-link p-0' %>
            <% end %> |
            <%= link_to 'Reply', '#', remote: true, onclick: 'toggleNextSibling(event, this); return false;', class: 'btn btn-link p-0' %>
          </div>
          <div class="reply-form-container" style="display: none; margin-top: 10px; width: 100%;">
            <%= render 'comments/reply_form', parent_id: comment.id %>
          </div>
     
      </div>

      <div class="ps-3">
        <% if comment.replies.any? %>
          <h4 class="fw-bold">Replies</h4>
          <% comment.replies.each do |reply| %> 
            <%= render 'comments/reply', reply: reply %> <br>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<% end %>

app/views/comments/_form.html.erb
<div>
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <p class="mt-3">
  <% if current_user %>
      <%= form.hidden_field :user_id, value: current_user.id %>
        <% @post.errors.full_messages_for(:user_id).each do |message| %>
        <div class="text-danger p-1"> <%= message %> </div>
      <% end %> 
  </p>

  <p>
    <%= form.label "Comment here: " %><br>
    <%= form.text_field :body, class: 'form-control' %>
        <% @post.errors.full_messages_for(:body).each do |message| %>
        <div class="text-danger p-1"> <%= message %> </div>
        <% end %> 
  </p>
  
  <p>
    <%= form.submit "Add Comment", class: 'btn btn-primary' %>
  </p>
<% end %>
<% end %>
</div>

app/views/comments/_reply.html.erb
<div>
  <strong><%= reply.user.name %></strong> : <%= reply.body %>
</div>
<div>
<div class="d-flex flex-row">
  <% if current_user.admin? %>
  
    <%= button_to 'Delete', [reply.post, reply], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link p-0' %> |
  <% end %>
  <% unless already_liked?(reply) %>
    <%= button_to 'Like', post_comment_likes_path(reply.post, reply), method: :post, class: 'btn btn-link p-0' %>
  <% else %>
    <%= button_to 'Unlike', post_comment_like_path(reply.post, reply, id: reply.likes.find_by(user_id: current_user.id)), method: :delete, class: 'btn btn-link p-0' %>
  <% end %> |
  <%= link_to 'Reply', '#', remote: true, onclick: 'toggleNextSibling(event, this); return false;', class: 'btn btn-link p-0' %>
</div>
<div class="reply-form-container" style="display: none; margin-top: 10px; width: 100%;">
  <%= render 'comments/reply_form', parent_id: reply.id %>
</div>
</div>
<div class="ps-3">
  <% if reply.replies.any? %>
    <% reply.replies.each do |reply| %> 
      <%= render 'comments/reply', reply: reply %> 
    <% end %>
  <% end %>
</div>

app/views/comments/_reply_form.html.erb
<div>
    <%= form_with(model: [@post, @comment]) do |f| %>
  
      <%= f.hidden_field :parent_id, value: parent_id %>
  
      <div class="form-group">
       
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <div class="mt-2">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="container">
<h1 class= "fw-bold">Hello, welcome to admin dashboard</h1>
<h4 class="fw-bold">List of users</h2>
<div class="container">
  <% @user.each do |user| %>
    <li><%= user.email %></li>
  <% end %>

</div>
</div>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>
  <body>
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: "all" %>
  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <%= javascript_include_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
  <%= render 'shared/navbar' %>
  <div class="container my-3">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/index.html.erb
<h1>Your Messages</h1>

<h2>Received Messages</h2>
<ul>
  <% @received_messages.each do |message| %>
    <li>
      <strong>From:</strong> <%= message.sender.name %> <br>
      <strong>Message:</strong> <%= message.body %>
    </li>
  <% end %>
</ul>

<h2>Sent Messages</h2>
<ul>
  <% @sent_messages.each do |message| %>
    <li>
      <strong>To:</strong> <%= message.receiver.name %> <br>
      <strong>Message:</strong> <%= message.body %>
    </li>
  <% end %>
</ul>

<%= link_to "Send a Message!", new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= form_for(@message) do |f| %>
  <div class="field">
    <%= f.label :receiver_id, 'To' %><br>
      <% User.all.each do |user| %>
          <%= f.radio_button :receiver_id, user.id %>
          <%= user.email %>
      <% end %>
  </div>
  <div class="w-50 my-2">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Send Message', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<div class="container">

<%= form_with model: @post do |form| %>
<p class="mt-3">
     <%= form.hidden_field :user_id, value: current_user.id %>
         <% @post.errors.full_messages_for(:user_id).each do |message| %>
      <div class="text-danger p-1"> <%= message %> </div>
      <% end %> 
  </p>
   <div class="mt-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
     <% @post.errors.full_messages_for(:title).each do |message| %>
      <div class="text-danger p-1"> <%= message %> </div>
      <% end %> 
    </div>

   <div class="mt-3">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
    <% @post.errors.full_messages_for(:description).each do |message| %>
       <div class="text-danger p-1"> <%= message %> </div>
      <% end %> 
    </div>

  <div class="mt-3">
    <%= form.label :category_id %>
    <%= form.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]}) %>
  </div>

  <div class="mt-3">
    <%= form.submit "Create Blog", class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<div class="container my-3">

</div>
<h1 class="fw-bold pb-3">Blog Posts</h1>

<div>
  <% @posts.each do |post| %>
    <div class="bg-light p-3 m-2"><p><%= link_to post.title, post, class: "fw-bold" %> <small>by: <%= post.user.name %></small><p></div>
  <% end %>
</div>
<div class="py-3">
  <%= link_to "New Blog Post", new_post_path, class: 'btn btn-primary' %>
</div>

app/views/posts/new.html.erb
<h1>Add a new Blog Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<div class="d-flex flex-row ">
<div class="w-50 me-3">
<h1><%= @post.title %></h1>
<p><%= @post.description %></p>
<p>Blog by: <strong><%= @post.user.email %></strong></p>

 <%= button_to 'Like', post_likes_path(@post, likeable_type: 'Post', likeable_id: @post.id), class: 'btn btn-link px-0', method: :post unless already_liked?(@post) %>
<%= button_to 'Unlike', post_like_path(@post, id: @post.likes.find_by(user_id: current_user.id).id, likeable_type: 'Post', likeable_id: @post.id), class: 'btn btn-link px-0', method: :delete if already_liked?(@post) %>

<%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes' %>
<br>
<%= link_to 'liked by', '#', class: 'post-like', onclick: 'toggleNextSiblingLike(event, this); return false;' %>


 <div style="display: none;">
<ul>
  <% @post.liking_users.each do |liker| %>
     <li class= "list-unstyled"><%= liker.name %></li>
  <% end %>
  </ul>
</div> 
</div>
<div class="w-50 me-3">
<h3 class="fw-bold">Comments</h3>
<%= render 'comments/form' %>
<%= render @comments %>
<% if current_user && (current_user.admin || @post.user == current_user) %>
<div> 
  <%= link_to "Edit Blog Post", edit_post_path(@post), class: 'btn btn-primary' %>
  <%= link_to "Delete Blog Post", post_path(@post), data: {
                                                    turbo_method: :delete,
                                                    turbo_confirm: "Are you sure?"}, class: 'btn btn-primary' %>
</div>
<% end %>
</div>
</div>
<script>
function toggleNextSiblingLike(event, element) {
    event.preventDefault();
    const nextSibling = element.nextElementSibling;
    if (nextSibling.style.display === 'block') {
        nextSibling.style.display = 'none';
    } else {
        nextSibling.style.display = 'block';
    }
}

function toggleNextSibling(event, element) {
    event.preventDefault();
    const nextSibling = element.parentNode.parentNode.querySelector('.reply-form-container');
    if (nextSibling.style.display === 'block') {
        nextSibling.style.display = 'none';
    } else {
        nextSibling.style.display = 'block';
    }
}
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand fw-bold fs-3" href="http://localhost:3000/">Blogger App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="row">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
         <% if user_signed_in? %>
         <strong class="my-3 me-5">Logged in as: <%= current_user.name %></strong>
          <li class="nav-link"><%= link_to "Home", root_path, class: 'btn btn-primary' %></li>
          <li class="nav-link"><%= link_to "About", static_pages_about_path, class: 'btn btn-primary' %></li>
          <li class="nav-link"><%= link_to "Inbox", messages_path, class: 'btn btn-primary' %></li>
          <% if current_user.admin? %>
             <li class="nav-link" ><%= link_to "Admin Dashboard", dashboard_index_path, class: 'btn btn-primary' %></li>
          <% end %>
          <li class="nav-link"><%= button_to "Log out", destroy_user_session_path, method: :delete, class: 'btn btn-primary' %></li>
          <% else %>
            <li class="nav-link"><%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %></li>
            <li class="nav-link"><%= link_to "Log in", new_user_session_path, class: 'btn btn-primary' %></li>
          <% end %>
        </ul>
      </div>
      </div>
    </div>
</nav>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>